import type { Stack, Template } from './types';

export const STACKS: Stack[] = [
  { id: 'animation', name: 'Animation', imageUrl: 'https://images.unsplash.com/photo-1581833971358-2c8b550f87b3?q=80&w=800&h=600&auto=format&fit=crop&ixlib=rb-4.0.3' },
  { id: 'aesthetics', name: 'Aesthetics', imageUrl: 'https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?q=80&w=800&h=600&auto=format&fit=crop&ixlib=rb-4.0.3' },
  { id: 'celebration', name: 'Celebration', imageUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?q=80&w=800&h=600&auto=format&fit=crop&ixlib=rb-4.0.3' },
  { id: 'clothes', name: 'Clothes', imageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=800&h=600&auto=format&fit=crop&ixlib=rb-4.0.3' },
  { id: 'flex', name: 'Flex', imageUrl: 'https://images.unsplash.com/photo-1605300263678-e53b4ca64658?q=80&w=800&h=600&auto=format&fit=crop&ixlib=rb-4.0.3' },
  { id: 'infographics', name: 'Infographics', imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=800&h=600&auto=format&fit=crop&ixlib=rb-4.0.3' },
  { id: 'looks', name: 'Looks', imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=800&h=600&auto=format&fit=crop&ixlib=rb-4.0.3' },
  { id: 'monuments', name: 'Monuments', imageUrl: 'https://images.unsplash.com/photo-1527891753122-ec3c698a39da?q=80&w=800&h=600&auto=format&fit=crop&ixlib=rb-4.0.3' },
  { id: 'posters', name: 'Posters', imageUrl: 'https://images.unsplash.com/photo-1534970028765-38ce47ef7d8d?q=80&w=800&h=600&auto=format&fit=crop&ixlib=rb-4.0.3' },
  { id: 'presentations', name: 'Presentations', imageUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=800&h=600&auto=format&fit=crop&ixlib=rb-4.0.3' },
  { id: 'sceneries', name: 'Sceneries', imageUrl: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?q=80&w=800&h=600&auto=format&fit=crop&ixlib=rb-4.0.3' },
  { id: 'thumbnail', name: 'Thumbnail', imageUrl: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?q=80&w=800&h=600&auto=format&fit=crop&ixlib=rb-4.0.3' },
];

const animationTemplates: Template[] = [
  {
    id: 'animation_template_1',
    name: 'Anime Figure',
    stackId: 'animation',
    imageUrl: 'https://images.unsplash.com/photo-1613376023733-0a7536aa4d63?q=80&w=600&h=800&auto=format&fit=crop&ixlib=rb-4.0.3',
    prompt: "Generate an anime-style figure photo placed on a desktop, presented from a casual, everyday snapshot perspective as if taken with a mobile phone. The figure model is based on the attached character photo, accurately reproducing the full body posture, facial expression, and clothing style of the person in the photo, ensuring the entire figure is fully rendered. The overall design is exquisite and detailed, with hair and clothing featuring natural, soft gradient colors and fine textures. The style leans towards Japanese anime, rich in detail, with realistic textures, and a beautiful appearance.",
    aspectRatio: '3:4',
  },
  {
    id: 'animation_template_2',
    name: 'Ghibli Style',
    stackId: 'animation',
    imageUrl: 'https://images.unsplash.com/photo-1578351184307-e16856c14a43?q=80&w=600&h=800&auto=format&fit=crop&ixlib=rb-4.0.3',
    prompt: "Redraw this photo in the enchanting and whimsical animation style of Studio Ghibli. Focus on soft, painterly backgrounds, expressive character designs, and a warm, nostalgic color palette.",
    aspectRatio: '3:4',
  },
  {
    id: 'animation_template_3',
    name: '3D Chibi Polaroid',
    stackId: 'animation',
    imageUrl: 'https://images.unsplash.com/photo-1629822355420-10a45937a353?q=80&w=600&h=800&auto=format&fit=crop&ixlib=rb-4.0.3',
    prompt: "Convert the character in the scene into a 3D chibi-style figure, placed inside a Polaroid photo. The photo paper is being held by a human hand. The character is stepping out of the Polaroid frame, creating a visual effect of breaking through the two-dimensional photo border and entering the real-world 3D space.",
    aspectRatio: '3:4',
  },
  {
    id: 'animation_template_4',
    name: 'Stepping Through',
    stackId: 'animation',
    imageUrl: 'https://images.unsplash.com/photo-1531379415763-6c7414da4546?q=80&w=600&h=800&auto=format&fit=crop&ixlib=rb-4.0.3',
    prompt: "A 3D chibi-style version of the person in the photo is stepping through a glowing portal, reaching out and holding the viewer’s hand. As the character pulls the viewer forward, they turn back with a dynamic glance, inviting the viewer into their world.\nBehind the portal is the viewer’s real-life environment: a typical programmer’s study with a desk, monitor, and laptop, rendered in realistic detail. Inside the portal lies the character’s 3D chibi world, inspired by the photo, with a cool blue color scheme that sharply contrasts with the real-world surroundings.\nThe portal itself is a perfectly elliptical frame glowing with mysterious blue and purple light, positioned at the center of the image as a gateway between the two worlds.\nThe scene is captured from a third-person perspective, clearly showing the viewer’s hand being pulled into the character’s world. Use a 2:3 aspect ratio.",
    aspectRatio: '3:4',
  },
  {
    id: 'animation_template_5',
    name: 'LEGO Minifigure',
    stackId: 'animation',
    imageUrl: 'https://images.unsplash.com/photo-1559899479-58a794025a4d?q=80&w=600&h=800&auto=format&fit=crop&ixlib=rb-4.0.3',
    prompt: "Generate a vertically-oriented image based on my uploaded photo, using the following prompt:\nClassic LEGO minifigure style in a miniature scene — an animal stands beside me. The color palette of the animal should match mine.\nPlease design the animal based on your understanding of me. You may choose any creature — real, surreal, or fantastical — that you feel best reflects my personality.\nThe entire scene is set within a transparent glass cube, with a minimalist interior design.\nThe base of the miniature is matte black with silver accents, following a clean and modern aesthetic.\nOn the base, there is an elegantly engraved nameplate in a refined serif font, displaying the name of the animal.\nThe lower part of the base subtly incorporates finely etched biological classification details, similar to a natural history museum display.\nThe overall composition should resemble a high-end collectible artwork: meticulously crafted, curated in style, and lit with refined lighting.\nBalance is key to the layout. The background should feature a smooth gradient transition from dark to light tones, selected to match the dominant color theme.",
    aspectRatio: '3:4',
  },
  {
    id: 'animation_template_6',
    name: 'Anime Badge',
    stackId: 'animation',
    imageUrl: 'https://images.unsplash.com/photo-1611894982245-42a138679b33?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "Based on the person in the attachment, generate a photo of an anime-style badge. Requirements:\nMaterial: Tassel\nShape: Circular\nMain subject: A hand holding the badge",
    aspectRatio: '3:4',
  },
  {
    id: 'animation_template_7',
    name: 'Pixar 3D Style',
    stackId: 'animation',
    imageUrl: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: 'Redraw the person in this photo in the iconic Pixar 3D animation style. Focus on expressive, rounded features, detailed textures, and cinematic lighting to bring them to life as a beloved character.',
    aspectRatio: '3:4',
  },
  {
    id: 'animation_template_8',
    name: 'Chibi Sticker Sheet',
    stackId: 'animation',
    imageUrl: 'https://images.unsplash.com/photo-1620027582882-c34015f6b3e7?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "Please create a set of 9 Chibi stickers featuring [the character in the reference image], arranged in a 3x3 grid.\nDesign requirements:\n- Transparent background.\n- 1:1 square aspect ratio.\n- Consistent Chibi Ghibli cartoon style with vibrant colors.\n- Each sticker must have a unique action, expression, and theme, reflecting diverse emotions like \"sassy, mischievous, cute, frantic\" (e.g., rolling eyes, laughing hysterically on the floor, soul leaving body, petrified, throwing money, foodie mode, social anxiety attack). Incorporate elements related to office workers and internet memes.\n- Each character depiction must be complete, with no missing parts.\n- Each sticker must have a uniform white outline, giving it a sticker-like appearance.\n- No extraneous or detached elements in the image.\n- Strictly no text, or ensure any text is 100% accurate (no text preferred).",
    aspectRatio: '1:1',
  },
];

const aestheticsTemplates: Template[] = [
  {
    id: `aesthetics_template_1`,
    name: `Minimalist Daylight Studio`,
    stackId: 'aesthetics',
    imageUrl: `https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=600&h=800&auto=format&fit=crop`,
    prompt: `{input person} in a minimalist white or soft pastel room, clean matte surfaces, diffused daylight, calm posture, balanced framing, Raymond editorial style with subtle cinematic realism.\nno harsh lighting, no cluttered background, no oversaturation, no blurry edges.no change in hairstyle , no background blur.`,
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_2',
    name: 'Warm Rustic Interior',
    stackId: 'aesthetics',
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} in warm rustic surroundings with brick walls, wood grains, and soft sunset glow, subtle earth tones, nostalgic cinematic depth, National Geographic photo quality.\nno neon colors, no artificial blur, no plastic textures, no modern city elements.no change in hairstyle , no background blur.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_3',
    name: 'Urban Alleyway Portrait',
    stackId: 'aesthetics',
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "{input person} posing confidently in a textured alleyway, graffiti walls, wet reflective street, cinematic contrast lighting, modern travel-magazine tone.\nno fantasy look, no flat lighting, no distortion, no extra people.no change in hairstyle , no background blur.",
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_4',
    name: 'Vibrant Fabric Market',
    stackId: 'aesthetics',
    imageUrl: 'https://images.unsplash.com/photo-1569186640300-0585f67b6b44?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} surrounded by colorful fabrics, hanging lights, woven textures, relaxed candid pose, warm soft daylight, lifestyle-magazine composition.\nno chaotic background, no heavy shadows, no color noise, no unrealistic patterns, no change in hairstyle, no background blur.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_5',
    name: 'Royal Luxury Portrait',
    stackId: 'aesthetics',
    imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} in elegant royal surroundings — marble floors, velvet drapes, gold accents, graceful posture, classic Raymond luxury portrait style. bend the person and the background perfectly\nno fantasy castle, no cartoon gold, no bright glare, no blur. no change in hairstyle, no background blur.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_6',
    name: 'Forest Sunlight Portrait',
    stackId: 'aesthetics',
    imageUrl: 'https://images.unsplash.com/photo-1504287459415-3a326a578a75?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} surrounded by forest greens and soft sunlight filtering through leaves, grounded natural pose, fresh cinematic tone like a National Geographic portrait.\nno foggy haze, no overexposure, no fake greenery, no flat tones. no change in hairstyle, no background blur. make him touch a tree with one hand',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_7',
    name: 'Futuristic Cityscape',
    stackId: 'aesthetics',
    imageUrl: 'https://images.unsplash.com/photo-1579762715118-a6f3d5087c7b?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} in a sleek hyper realistic futuristic cityscape, soft reflections on glass and steel, balanced light blue tones, confident modern posture, cinematic clarity.\nno harsh neon, no heavy glow, no distortion, no cartoon rendering. no change in hairstyle, no background blur. make the person sit on a chair',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_8',
    name: 'Ancient Monument Portrait',
    stackId: 'aesthetics',
    imageUrl: 'https://images.unsplash.com/photo-1527891753122-ec3c698a39da?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} in traditional attire before an ancient monument or market street, warm daylight, authentic textures, respectful elegant posture, National Geographic realism.\nno artificial props, no fantasy color, no blur, no mixed cultural elements, no change in hairstyle, no background blur. make person join his hand and bow his head',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_9',
    name: 'Seaside Golden Hour',
    stackId: 'aesthetics',
    imageUrl: 'https://images.unsplash.com/photo-1615785805386-06e2679d3910?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} by the seaside or cliffside boardwalk, wind in hair and fabric, soft golden-hour tones, reflective water highlights, cinematic tranquility.\nno flat sky, no digital artifacts, no over-bright waves, no harsh shadows ,no background blur.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_10',
    name: 'Artistic Studio Portrait',
    stackId: 'aesthetics',
    imageUrl: 'https://images.unsplash.com/photo-1544006659-f0b21884ce18?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} in a textured artistic studio backdrop, controlled soft lighting, creative shadow play, fine-grain realism, magazine-cover tone, make him look in an isometric direction, with gradient shades.\nno uneven lighting, no excessive contrast, no blur, no clutter, no change in hairstyle ,no background blur.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_11',
    name: 'Elegant Silk Saree',
    stackId: 'aesthetics',
    imageUrl: 'https://images.unsplash.com/photo-1622353457204-2b73b54728d8?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} in an elegant silk saree with subtle jewelry, soft golden daylight, traditional Indian interior or temple courtyard, graceful posture, cinematic realism, Raymond-style sophistication.\nno overexposure, no heavy ornaments, no cartoon colors, no background blur.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_12',
    name: 'Tailored Blazer Professional',
    stackId: 'aesthetics',
    imageUrl: 'https://images.unsplash.com/photo-1617922001439-44b4833a8258?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} in a tailored blazer and trousers, minimalist corporate studio background with soft daylight, confident posture, modern lifestyle tone, Raymond editorial clarity.\nno harsh lighting, no low contrast, no busy background, no flat colors. change the hand gestures according to the background.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_13',
    name: 'Bohemian Chic',
    stackId: 'aesthetics',
    imageUrl: 'https://images.unsplash.com/photo-1508215893541-45548f03e1b9?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} in layered bohemian fabrics and patterns, soft evening sunlight, textured studio or artistic street market setting, natural smile, free-spirited hyper realistic image.\nno neon tones, no clutter, no artificial blur, no plastic texture , no background blur, change the hand gestures according to the background, no change in hairstyle.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_14',
    name: 'Evening Gown Twilight',
    stackId: 'aesthetics',
    imageUrl: 'https://images.unsplash.com/photo-1597084534839-24fd5d1a892b?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} in a flowing satin gown, standing in a softly lit ballroom or terrace at twilight, subtle reflections, rich color contrast, high-end magazine style realism.\nno glare, no fantasy glow, no distorted proportions, no over-saturation. no background blur, change the hand gestures according to the background, no change in hairstyle.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_15',
    name: 'Modern Casual City',
    stackId: 'aesthetics',
    imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} in modern casual wear — jeans, light top, sneakers — city backdrop with graffiti walls or cozy café vibe, relaxed pose, cinematic lifestyle look.\nno washed-out colors, no messy framing, no extra people, no cartoon tone. no background blur, change the hand gestures according to the background, no change in hairstyle.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_16',
    name: 'Vintage 1950s Style',
    stackId: 'aesthetics',
    imageUrl: 'https://images.unsplash.com/photo-1605368434250-73f619b0a1d4?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} in a 1950s-inspired dress, vintage car or old café in background, warm muted tones, nostalgic mood, hyper-realistic Raymond heritage tone.\nno digital artifacts, no bright neon, no blur, no modern elements. no background blur, change the hand gestures according to the background, no change in hairstyle.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_17',
    name: 'Festive Ethnic Wear',
    stackId: 'aesthetics',
    imageUrl: 'https://images.unsplash.com/photo-1581338834928-14571f38531f?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} in festive ethnic wear, vibrant backdrop with lamps or drapes, glowing warm light, cultural richness with realistic color depth and fabric texture.\nno overexposed lights, no cartoon look, no fake background, no blur. no background blur, change the hand gestures according to the background, no change in hairstyle.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_18',
    name: 'Pastel Professional',
    stackId: 'aesthetics',
    imageUrl: 'https://images.unsplash.com/photo-1572804013427-4d7ca7268217?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} in light pastel blouse and trousers, airy daylight studio, subtle pastel background, Raymond lifestyle tone, clean lines, professional yet approachable look.\nno harsh lighting, no color oversaturation, no cartoon tone, no blurriness. no background blur, change the hand gestures according to the background, no change in hairstyle.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_19',
    name: 'Serene Landscape Portrait',
    stackId: 'aesthetics',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723a9ce6ad3?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} in simple earthy outfit surrounded by tall grass or mountain landscape, golden-hour sunlight, serene composition, cinematic National Geographic realism.\nno fog blur, no harsh shadows, no flat lighting, no digital noise. no background blur, change the hand gestures according to the background, no change in hairstyle.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_20',
    name: 'Dramatic Studio Portrait',
    stackId: 'aesthetics',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} posing in an artistic indoor setup with textured painted backdrop, soft spot lighting, dramatic shadows, portrait realism with magazine clarity.\nno uneven tone, no distortion, no harsh contrast, no clutter. no background blur, change the hand gestures according to the background, no change in hairstyle.',
    aspectRatio: '3:4',
  },
];


const celebrationTemplates: Template[] = [
    {
      id: 'celebration_template_1',
      name: 'Birthday Confetti Blast',
      stackId: 'celebration',
      imageUrl: 'https://images.unsplash.com/photo-1512433217458-d4f4b93457a9?q=80&w=600&h=800&auto=format&fit=crop',
      prompt: 'Place the person from the photo into a vibrant, high-energy birthday celebration. The person must be seamlessly composited, standing realistically on a floor. Ensure the color temperature and quality of light on the person perfectly matches the party lights. Ground the person with a soft, believable contact shadow on the floor. The edges of the person\'s silhouette must be perfectly anti-aliased and softly feathered for a seamless blend into the background. Surround them with a dynamic shower of multi-colored, metallic confetti frozen in mid-air. The background should be filled with festive party decorations and colorful balloons with a shallow depth of field. Critically, the person\'s face, features, and hairstyle must be an exact, photorealistic match of the original photo and must not be altered. Negative prompt: no altered faces, no changed facial features.',
      aspectRatio: '3:4',
    },
    {
      id: 'celebration_template_2',
      name: 'Diwali Celebration',
      stackId: 'celebration',
      imageUrl: 'https://images.unsplash.com/photo-1604202359784-4fe12c9e6e96?q=80&w=600&h=800&auto=format&fit=crop',
      prompt: "A portrait of the person in the provided photo celebrating Diwali. They must be seamlessly composited into the scene, realistically positioned and surrounded by bright diyas and intricate rangoli patterns. The warm, golden light from the diyas must cast realistic, soft highlights on the person, matching the color temperature and direction of the ambient light. Their edges must be seamlessly blended with the background, using soft feathering to avoid any harsh cutout lines. They must be grounded with accurate, soft contact shadows. Use sparkling fairy lights and sparklers in the background, festive Indian attire, cinematic lighting, and a bokeh effect for ultra-detailed photography. Critically, the person's face, features, and hairstyle must be an exact, photorealistic match of the original photo and must not be altered. Negative prompt: no altered faces, no changed facial features.",
      aspectRatio: '3:4',
    },
    {
      id: 'celebration_template_3',
      name: 'Cozy Christmas Portrait',
      stackId: 'celebration',
      imageUrl: 'https://images.unsplash.com/photo-1607537657731-5964de2a23a8?q=80&w=600&h=600&auto=format&fit=crop',
      prompt: "A cozy festive portrait of the person from the provided photo, seamlessly placed beside a beautifully decorated Christmas tree, standing on a floor or a cozy rug. It is crucial that the warm, yellow lights from the tree cast soft, realistic highlights and colored light spill onto the person, with lighting and shadows that perfectly match. The figure must be grounded with soft, diffused contact shadows on the floor/rug. The edges of the person must be seamlessly blended into the cozy scene, with no hard outlines. The scene is adorned with sparkling ornaments and wrapped gifts, surrounded by gently falling snowflakes. The subject wears stylish winter attire. Critically, the person's face, features, and hairstyle must be an exact, photorealistic match of the original photo and must not be altered. Negative prompt: no cartoon style, no Santa hats on random objects, no duplicate faces, no messy composition, no altered faces, no changed facial features.",
      aspectRatio: '1:1',
    },
    {
      id: 'celebration_template_4',
      name: 'Holi Celebration',
      stackId: 'celebration',
      imageUrl: 'https://images.unsplash.com/photo-1616425120121-08172c0cac45?q=80&w=600&h=800&auto=format&fit=crop',
      prompt: 'A photo of the person from the provided photo, celebrating Holi. They must be seamlessly integrated into the scene, grounded realistically and interacting with their environment. The ambient daylight must realistically light the subject, with highlights and shadows consistent with an outdoor scene. Splashes of color powder should appear on their clothes and skin naturally. Ensure their edges are perfectly blended with the dynamic background of airborne color powder, avoiding any sharp, artificial outlines. Traditional attire, warm daylight, cinematic motion blur. Sharp focus on the face. Critically, the person\'s face, features, and hairstyle must be an exact, photorealistic match of the original photo and must not be altered. Negative prompt: no messy background, no paint on camera lens, no color oversaturation, no duplicates, no altered faces, no changed facial features.',
      aspectRatio: '3:4',
    },
    {
      id: 'celebration_template_5',
      name: 'Elegant Eid Portrait',
      stackId: 'celebration',
      imageUrl: 'https://images.unsplash.com/photo-1574631899513-4a11f8b44859?q=80&w=600&h=800&auto=format&fit=crop',
      prompt: "A graceful portrait of the person from the provided photo, seamlessly placed within a beautifully decorated room, wearing elegant festive attire. They should be standing or seated realistically, well-integrated with correct perspective. The warm evening light from golden lamps must cast a soft, realistic glow on the person, matching the color temperature and creating a cohesive mood. Their silhouette must be cleanly and softly blended with the background, with feathered edges to prevent a cutout appearance. They must be grounded with accurate, soft shadows. Surrounded by crescent moon decorations and traditional patterns. Critically, the person's face, features, and hairstyle must be an exact, photorealistic match of the original photo and must not be altered. Negative prompt: no religious symbols distortion, no dark filters, no harsh shadows, no altered faces, no changed facial features.",
      aspectRatio: '3:4',
    },
];

const clothesTemplates: Template[] = [
  {
    id: 'clothes_template_1',
    name: 'Maharaja Majesty',
    stackId: 'clothes',
    imageUrl: 'https://images.unsplash.com/photo-1634356795029-397a2f268feb?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "A hyper-realistic image of {input person} wearing a traditional Indian Maharaja outfit — embroidered sherwani with regal turban, intricate jewelry, and rich velvet texture. The person's face and features must be an exact match of the provided photo, without any alterations. The person should be seamlessly integrated, standing realistically on a clean studio floor with accurate contact shadows. The warm studio lighting must realistically wrap around the subject, matching the color temperature and creating cohesive highlights and shadows for a believable portrait. The background is a soft cinematic blur. National Geographic x Raymond fashion aesthetic. Ultra-sharp fabric detail, lifelike skin tone.\nno cartoon embroidery, no plastic jewelry, no harsh flash, no duplicate faces, no low-quality fabric texture, no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_2',
    name: 'Classic Tailored Suit',
    stackId: 'clothes',
    imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "{input person} in a tailored charcoal or navy suit with white shirt and silk tie. The person's face and features must be an exact match of the provided photo, without any alterations. Their integration into the studio setup must be seamless, with their feet firmly planted, casting a soft, realistic shadow. The soft studio lighting on the subject should perfectly match the subtle gradient background, creating realistic dimensionality and soft shadows. Editorial-grade Raymond-style realism, 8K cinematic photography, balanced highlights, lifelike shadowing, clean grooming, polished texture.\nno exaggerated contrast, no wrinkled suit, no off-tone skin, no duplicate background, no low detail, no change in hairstyle, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_3',
    name: 'Business Casual',
    stackId: 'clothes',
    imageUrl: 'https://images.unsplash.com/photo-1627993093033-65c4c95a8b6e?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "A professional portrait of {input person} in business casual attire — light blazer, rolled-sleeve shirt, and chinos. The person's face and features must be an exact match of the provided photo, without any alterations. The person should be realistically placed in the scene, with the natural daylight from the window creating believable highlights and soft shadows on them that perfectly match the color and direction of the light in the blurred office background. The result should be a cohesive, cinematic, and sharp image with a seamless blend between the subject and the environment. Raymond-style color grading.\nno cluttered background, no cartoon tone, no distorted fabric folds, no mixed lighting, no change in hair style, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_4',
    name: 'Modern Festive Kurta',
    stackId: 'clothes',
    imageUrl: 'https://images.unsplash.com/photo-1617137984847-5a56335c10643?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "{input person} wearing a modern festive kurta with subtle embroidery, paired with churidar pants. The person's face and features must be an exact match of the provided photo, without any alterations. The person should be seamlessly placed in the scene, with elegant traditional lighting and soft bokeh from warm lamps creating realistic highlights on their attire that match the color temperature of the lights. Ensure crisp shadows and color-balanced tones for a cohesive look. Raymond-style realism with ultra-detailed textures.\nno over-bright lights, no duplicate person, no fabric distortion, no fantasy color filters,no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_5',
    name: 'Indo-Western Fusion',
    stackId: 'clothes',
    imageUrl: 'https://images.unsplash.com/photo-1631163456372-a726615b3992?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "A stylish photo of {input person} in Indo-Western fusion attire — long jacket with modern cuts, layered with shirt or kurta inside. The person's face and features must be an exact match of the provided photo, without any alterations. Ensure the person is seamlessly integrated with the subtle background gradient. The cinematic studio lighting should realistically illuminate the subject, creating highlights and shadows that give a cohesive, high-fashion look against the subtle background. High fashion Raymond realism, 8K fabric texture.\nno over-stylized design, no excessive jewelry, no mismatched colors, no soft blur, no change in hairstyle , no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_6',
    name: 'Premium Winter Fashion',
    stackId: 'clothes',
    imageUrl: 'https://images.unsplash.com/photo-1611312449412-6cefac58c24f?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "{input person} dressed in premium winter fashion — wool coat, turtleneck, and scarf. The person's face and features must be an exact match of the provided photo, without any alterations. They must be perfectly blended with the neutral tone background, with soft, cool-toned directional lighting creating subtle, realistic shadows on their form and attire that match the neutral background. Cinematic Raymond ad aesthetic, hyper-realistic texture, 85 mm lens photo realism.\nno overly dark tones, no duplicate coats, no blur, no fantasy lighting,no change in hairstyle , no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_7',
    name: '1950s Gentleman',
    stackId: 'clothes',
    imageUrl: 'https://images.unsplash.com/photo-1605368434250-73f619b0a1d4?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "A portrait of {input person} styled as a 1950s gentleman — double-breasted suit, classic haircut, pocket square. The person's face and features must be an exact match of the provided photo, without any alterations. The person must be seamlessly placed against the studio backdrop. The sepia-toned cinematic lighting should cast realistic, soft shadows consistent with a single studio light source, creating a cohesive, vintage look. Hyper-realistic fabric detail, Raymond x National Geographic tone balance.\nno grainy filters, no vintage blur, no unrealistic shadows, no excessive sepia, no change in hairstyle , no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_8',
    name: 'Wedding Sherwani',
    stackId: 'clothes',
    imageUrl: 'https://images.unsplash.com/photo-1634356795029-397a2f268feb?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "{input person} wearing a luxurious wedding sherwani with golden embroidery, dupatta over shoulder. The person's face and features must be an exact match of the provided photo, without any alterations. The person should be seamlessly integrated into the scene, with elegant lighting from the royal interior setting realistically illuminating the detailed fabric, matching the color and direction of the ambient light for a cohesive look. Raymond-style composition, cinematic 8K realism.\nno glare, no duplicate jewelry, no fake palace, no excessive glow. no change in hairstyle , no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_9',
    name: 'Summer Linen',
    stackId: 'clothes',
    imageUrl: 'https://images.unsplash.com/photo-1595343472535-c355ab7b4279?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "A lifestyle portrait of {input person} in a light linen shirt and chinos. The person's face and features must be an exact match of the provided photo, without any alterations. The person must be naturally blended into the sunny outdoor ambience, with soft daylight filtering through leaves to cast realistic, dappled shadows on them, ensuring the light's color and intensity match a sunny outdoor setting. Raymond summer campaign aesthetic, photorealistic tone, clean colors.\nno sweat, no cartoon tones, no distorted hands, no unrealistic lighting, no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_10',
    name: 'Silk Saree',
    stackId: 'clothes',
    imageUrl: 'https://images.unsplash.com/photo-1622353457204-2b73b54728d8?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "A hyper-realistic portrait of {input person} wearing a rich silk saree with detailed zari border, styled hair and traditional jewelry. The person's face and features must be an exact match of the provided photo, without any alterations. The person must be seamlessly integrated with the minimal studio background. Soft, warm studio lighting should realistically illuminate the subject and the fabric's texture, creating cohesive highlights and shadows for a cinematic, editorial-style image. Ultra-sharp texture and lifelike folds.\nno plastic jewelry, no over-saturated reds, no cartoon shine, no duplicate drapes,no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_11',
    name: 'Evening Gown',
    stackId: 'clothes',
    imageUrl: 'https://images.unsplash.com/photo-1597084534839-24fd5d1a892b?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "{input person} in a flowing evening gown. The person's face and features must be an exact match of the provided photo, without any alterations. The person should be seamlessly placed against the subtle gradient backdrop. Elegant studio light must create smooth, realistic highlights and shadows on the fabric that give it form and depth against the backdrop. High-fashion cinematic tone.\nno blur, no fantasy sparkles, no duplicated arms, no overexposure, no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_12',
    name: 'Tailored Blazer',
    stackId: 'clothes',
    imageUrl: 'https://images.unsplash.com/photo-1617922001439-44b4833a8258?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "A professional portrait of {input person} in a tailored blazer and trousers. The person's face and features must be an exact match of the provided photo, without any alterations. The person should be realistically blended with the minimal office backdrop, with soft, neutral studio lighting creating crisp folds and natural shadows for a cohesive, editorial look against the minimal backdrop. Raymond ad realism, professional fashion tone.\nno harsh reflections, no messy hair, no blur, no distorted proportions, no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_13',
    name: 'Boho Dress',
    stackId: 'clothes',
    imageUrl: 'https://images.unsplash.com/photo-1508215893541-45548f03e1b9?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "{input person} wearing a flowy printed boho dress with light accessories. The person's face and features must be an exact match of the provided photo, without any alterations. The person must be naturally integrated into the outdoor scene, with daylight realistically filtering through foliage to create warm sun flares and soft, dappled shadows on them, perfectly matching an outdoor, sunny environment. National Geographic × Raymond cinematic realism, soft natural tones, ultra-detailed texture.\nno fake patterns, no crowd, no lens flare over face, no heavy color grading, no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_14',
    name: 'Knit Turtleneck',
    stackId: 'clothes',
    imageUrl: 'https://images.unsplash.com/photo-1575409170322-a5f1122ba6ac?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "{input person} dressed in a wool coat, knit turtleneck, and scarf. The person's face and features must be an exact match of the provided photo, without any alterations. They must be seamlessly blended into the studio setting, with soft, cool-toned studio light creating realistic, cinematic shadows that match the winter fashion theme. Premium Raymond-style realism, fabric grain visible in 8K detail.\nno dark noise, no blur, no exaggerated cold tone, no duplicate coat layers,no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_15',
    name: 'Indo-Western Ensemble',
    stackId: 'clothes',
    imageUrl: 'https://images.unsplash.com/photo-1598164741691-177d6a52416b?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "{input person} wearing an Indo-Western ensemble — tailored jacket over long skirt or trousers, elegant jewelry accents. The person's face and features must be an exact match of the provided photo, without any alterations. The person should be seamlessly integrated into the scene, with cinematic editorial lighting creating cohesive highlights and shadows for a high-fashion magazine look. Raymond tone balance, ultra-sharp clothing detail.\nno cluttered background, no fantasy glow, no distorted fabric, no duplicate jewelry, no change in hair style, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_16',
    name: 'Bridal Lehenga',
    stackId: 'clothes',
    imageUrl: 'https://images.unsplash.com/photo-1631624838382-79942a4208a3?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "A National Geographic-grade image of {input person} in a detailed bridal lehenga. The person's face and features must be an exact match of the provided photo, without any alterations. The person must be seamlessly composited, with intricate embroidery shining realistically under soft golden light, ensuring the highlights and shadows on the subject are cohesive with the light source. The lighting should create a natural elegance and a gentle background blur for a cohesive look. Raymond ad color tone, hyper-realistic textures.\nno duplicate faces, no plastic shine, no artificial color filters, no glare, no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_17',
    name: 'Pastel Blouse',
    stackId: 'clothes',
    imageUrl: 'https://images.unsplash.com/photo-1572804013427-4d7ca7268217?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "{input person} in a light pastel blouse and trousers. The person's face and features must be an exact match of the provided photo, without any alterations. The person must be seamlessly integrated into the airy daylight studio setting. The bright, airy studio lighting and subtle pastel background should create a clean, professional, and cohesive image, with soft, flattering shadows. Raymond lifestyle aesthetic, cinematic realism.\nno harsh lighting, no color oversaturation, no cartoon tone, no blurriness, no change in hairstyle , no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
];

const flexTemplates: Template[] = [
  {
    id: 'flex_template_1',
    name: 'Bugatti Coastal Drive',
    stackId: 'flex',
    imageUrl: 'https://images.unsplash.com/photo-1614262145118-348520336923?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} in a tailored suit or premium jacket, posing beside or driving a Bugatti on a scenic coastal highway, sunlight reflecting off polished metal, wind-in-motion realism, Raymond-class sophistication.\nno motion blur, no fantasy reflections, no cartoon look, no harsh shadows.',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_2',
    name: 'Luxury Superbike Rider',
    stackId: 'flex',
    imageUrl: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} in sleek riding gear with a luxury superbike (like Ducati, BMW, or Hayabusa), mountains or city lights in background, cinematic dust trail, hyper-real fabric and metal textures, confident Raymond posture.\nno artificial glow, no blur, no color oversaturation, no background noise, no change in hairstyle, no blur background, change the hand gestures accordingly',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_3',
    name: 'Ice Rink Elegance',
    stackId: 'flex',
    imageUrl: 'https://images.unsplash.com/photo-1533202029019-33165275a2d8?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} gliding across a glassy ice rink wearing a stylish winter outfit — wool coat, gloves, and scarf, soft white lighting, reflections on ice, hyper-real fabric and frost details, serene elegance.\nno blur, no fantasy snow, no overexposure, no messy reflections.no change in hairstyle , no blur background, change the hand gestures accordingly',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_4',
    name: 'Deep Sea Diver',
    stackId: 'flex',
    imageUrl: 'https://images.unsplash.com/photo-1577292550932-808061a1215e?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} underwater wearing a professional diving suit, surrounded by coral reefs and sunlight rays filtering through water, vibrant blue tones, National Geographic underwater realism with cinematic balance.\nno foggy water, no over-bright color, no blur, no unrealistic fish.no change in hairstyle , no blur background, change the hand gestures accordingly',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_5',
    name: 'Private Jet Lifestyle',
    stackId: 'flex',
    imageUrl: 'https://images.unsplash.com/photo-1623998132172-a00333b2f2b7?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} boarding or seated beside a private jet, dressed in formal-casual attire — blazer and sunglasses, golden sunset light, tarmac reflections, refined Raymond elegance and cinematic composition.\nno glare, no distorted jet, no cartoon tones, no excessive brightness.no change in hairstyle , no blur background, change the hand gestures accordingly',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_6',
    name: 'Yacht Life',
    stackId: 'flex',
    imageUrl: 'https://images.unsplash.com/photo-1595034654378-9e0c6579301e?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} on a luxury yacht deck wearing linen shirt or summer blazer, calm blue ocean background, sunlight reflections on water, clean cinematic tones, National Geographic-style travel luxury.\nno haze, no overexposure, no blur, no unrealistic waves.no change in hairstyle , no blur background, change the hand gestures accordingly',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_7',
    name: 'City Night Supercar',
    stackId: 'flex',
    imageUrl: 'https://images.unsplash.com/photo-1617651036034-e4745b7a1e5a?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} in a black or navy blazer, leaning on a Lamborghini or McLaren under neon city lights, cinematic reflections on car surfaces, confident luxury tone, editorial realism.\nno cartoon neon, no fantasy lighting, no distortion, no change in hairstyle , no blur background, change the hand gestures accordingly',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_8',
    name: 'Desert ATV Adventure',
    stackId: 'flex',
    imageUrl: 'https://images.unsplash.com/photo-1534969974815-537449a216e5?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} on a rugged ATV or dirt bike, desert dunes in the background, soft golden sand tones, high-texture realism with wind dust, adventure-focused yet stylish Raymond tone.\nno low detail sand, no motion blur, no over-saturation, no distortion. no change in hairstyle , no blur background, change the hand gestures accordingly',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_9',
    name: 'Sunset Convertible Drive',
    stackId: 'flex',
    imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=800&h=600&auto=format&fit=crop',
    prompt: '{input person} driving a convertible through a scenic coastal road at sunset, soft warm light, detailed car reflections, relaxed posture, cinematic Raymond tone of leisure and freedom.\nno glare, no blur, no fantasy colors, no distorted vehicle.no change in hairstyle , no blur background, change the hand gestures accordingly . whole face should be visible',
    aspectRatio: '4:3',
  },
  {
    id: 'flex_template_10',
    name: 'Luxury Hotel Lounge',
    stackId: 'flex',
    imageUrl: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} in a formal blazer or elegant dress, seated in a luxurious hotel lounge with warm ambient lighting, marble tables, golden tones, cinematic realism, Raymond lifestyle grace and poise.\nno harsh light, no blur, no busy crowd, no cartoon textures.no change in hairstyle , no blur background, change the hand gestures accordingly . whole face should be visible .',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_11',
    name: 'Premium Wristwatch',
    stackId: 'flex',
    imageUrl: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} adjusting a premium wristwatch (Rolex, Omega, etc.), wearing a fitted suit, soft golden light highlighting metallic reflections, focus on texture and class, Raymond editorial clarity.\nno overexposure, no fingerprints glare, no blur, no fantasy glow.no change in hairstyle , no  background blur, change the hand gestures accordingly. whole face should be visible .',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_12',
    name: 'Luxury Shopping Spree',
    stackId: 'flex',
    imageUrl: 'https://images.unsplash.com/photo-1555529771-835f59fc5efe?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} walking through a luxury shopping district or high-end boutique, holding branded shopping bags, stylish modern outfit, cinematic natural lighting and color realism.\nno crowd, no harsh neon, no motion blur, no washed tones. no change in hairstyle , no  background blur, change the hand gestures accordingly. whole face should be visible .',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_13',
    name: 'Infinity Pool Villa',
    stackId: 'flex',
    imageUrl: 'https://images.unsplash.com/photo-1561027585-7553f0f9b6b0?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} relaxing in a private villa terrace with infinity pool, wearing casual linen attire, golden sunlight reflecting on water, serene Raymond lifestyle tone, high-end vacation realism ,8k quality image .\nno unrealistic sky, no blur, no fantasy pool reflection, no saturation spike. no change in hairstyle , no  background blur, change the hand gestures accordingly . whole face should be visible .',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_14',
    name: 'Morning Coffee & Journal',
    stackId: 'flex',
    imageUrl: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} sitting beside a wooden table with a coffee cup and leather journal, warm morning light streaming in, casual yet refined outfit, Raymond editorial lifestyle clarity.\nno low-light noise, no over-bright mug, no harsh shadows, no change in hairstyle , no  background blur, change the hand gestures accordingly . whole face should be visible .',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_15',
    name: 'Modern Gym Session',
    stackId: 'flex',
    imageUrl: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} in a sleek modern gym, wearing premium sportswear, cinematic light streaks across metal equipment, posture showing focus and discipline, Raymond athletic luxury vibe.\nno cluttered background, no blur, no over-saturation, no artificial tone. no change in hairstyle , no  background blur, change the hand gestures accordingly . whole face should be visible .',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_16',
    name: 'Fine Dining Experience',
    stackId: 'flex',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} at a fine dining table, elegant evening wear, candlelight and reflections from wine glasses, warm cinematic tone, Raymond lifestyle luxury captured with realism.\nno messy background, no glare, no fantasy color, no blur. no change in hairstyle , no  background blur, change the hand gestures accordingly . whole face should be visible .',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_17',
    name: 'Luxury Hotel Suite',
    stackId: 'flex',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} relaxing or preparing in a high-end suite, elegant interior textures, soft lamp light and silk bedding, refined comfort and subtle cinematic warmth, Raymond-class composition.\nno harsh lighting, no blur, no fake props, no color imbalance.no change in hairstyle , no  background blur, change the hand gestures accordingly . whole face should be visible .',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_18',
    name: 'Race Track Ferrari',
    stackId: 'flex',
    imageUrl: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: '{input person} standing beside a red Ferrari in a race track pit wearing a tailored race suit, dynamic composition, crisp sunlight, polished reflections, hyper-realistic fashion-meets-speed vibe, Raymond luxury tone.\nno lens distortion, no cartoon color, no blur, no empty background, no plastic reflections..no  background blur, change the hand gestures accordingly . whole face should be visible .',
    aspectRatio: '3:4',
  },
];

const monumentsTemplates: Template[] = [
  {
    id: 'monuments_template_1',
    name: 'Taj Mahal Sunrise Portrait',
    stackId: 'monuments',
    imageUrl: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "A hyper-realistic portrait of the person from the provided photo, seamlessly composited onto the marble walkway near the Taj Mahal at sunrise. Critically, their face, features, and hairstyle must be an exact, photorealistic match to the user's photo and must not be altered. The lighting on them must perfectly match the color temperature and soft quality of the sunrise, with highlights and shadows consistent with the sun's direction. Their feet must be firmly on the ground, casting a soft, accurate contact shadow on the marble. Their edges must be seamlessly blended with the misty background. Digitally dress them in elegant Indian travel attire. The background shows the Yamuna River mist, with a calm, majestic atmosphere. Cinematic 8K detail. \nno washed-out sky, no tourists, no fake reflections, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'monuments_template_2',
    name: 'Eiffel Tower Romance',
    stackId: 'monuments',
    imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760c0341?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "Place the person from the photo in a romantic, cinematic scene in Paris, with the Eiffel Tower in the background at golden hour. The person's face, features, and hairstyle must be preserved with photorealistic accuracy and must not be altered. The person must be seamlessly composited, for example, leaning realistically on a classic Parisian balcony railing. The warm, golden hour light must wrap around the subject naturally, creating soft highlights and shadows that match the color temperature and direction of the ambient light. Ensure their edges are soft and perfectly blended into the background. Digitally dress them in chic, stylish attire. The mood should be dreamy and romantic, with a shallow depth of field. \nno altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'monuments_template_3',
    name: 'Pyramids of Giza Expedition',
    stackId: 'monuments',
    imageUrl: 'https://images.unsplash.com/photo-158862482-135a513c23e8?q=80&w=800&h=450&auto=format&fit=crop',
    prompt: "Create a grand, adventurous shot of the person from the photo, seamlessly integrated into the scene at the Pyramids of Giza. Their face, features, and hairstyle must remain identical to the uploaded photo and not be altered. They must be standing firmly on the desert sand, with the bright desert sun casting strong, realistic shadows that ground them in the environment. The lighting on the person must match the harsh, direct sunlight of the desert. Ensure their edges are cleanly blended against the background. Position them as an explorer in practical clothing. The final image should feel like a still from an epic adventure movie. \nno altered faces, no changed facial features.",
    aspectRatio: '16:9',
  },
  {
    id: 'monuments_template_4',
    name: 'Statue of Liberty Welcome',
    stackId: 'monuments',
    imageUrl: 'https://images.unsplash.com/photo-1546271927-41a4574b25e7?q=80&w=800&h=600&auto=format&fit=crop',
    prompt: "Create a powerful portrait of the person from the photo, seamlessly placed on a paved pathway on Liberty Island, with the Statue of Liberty in the background. Maintain the person's facial features and hairstyle with absolute accuracy; do not alter them. They must be realistically grounded with shadows that are consistent with the bright daylight. The lighting on the person must perfectly match the bright, outdoor daylight. Ensure their silhouette is cleanly and seamlessly blended with the background. Digitally dress them in casual tourist attire. The image should be crisp, clear, and vibrant. \nno altered faces, no changed facial features.",
    aspectRatio: '4:3',
  },
  {
    id: 'monuments_template_5',
    name: 'Great Wall of China Trek',
    stackId: 'monuments',
    imageUrl: 'https://images.unsplash.com/photo-1508804185884-3c19b52a4128?q=80&w=800&h=450&auto=format&fit=crop',
    prompt: "Place the person from the photo onto a majestic section of the Great Wall of China. The person's face and hairstyle must be an exact match to the input photo and must not be altered. They must be seamlessly composited, standing firmly on the stone walkway with a view of rolling mountains. The natural daylight must illuminate the person realistically, matching the color and direction of the sun, creating shadows that ground them in the scene. Their edges must be naturally blended with the background. Digitally dress them in practical trekking gear. The mood should be one of adventure and awe. \nno altered faces, no changed facial features.",
    aspectRatio: '16:9',
  },
  {
    id: 'monuments_template_6',
    name: 'Colosseum Gladiator Pose',
    stackId: 'monuments',
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "Compose a dramatic image of the person from the photo, seamlessly integrated into a scene before the Colosseum in Rome. Do not alter their face, features, or hairstyle. They must be standing realistically on the ground, with the golden hour light casting long, believable shadows that anchor them to the spot. The warm light must wrap around their form convincingly, matching the color temperature of the scene. Ensure their edges are clean and seamlessly blended with the background. Dress them in stylish, modern attire. The final image should be high-contrast and heroic. \nno altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'monuments_template_7',
    name: 'Lotus Temple Sunset Portrait',
    stackId: 'monuments',
    imageUrl: 'https://images.unsplash.com/photo-1587740263150-e4b9fae4a737?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "Create a serene and hyper-realistic portrait of the person from the provided photo, seamlessly composited onto the walkway beside a reflecting pool at the Lotus Temple in Delhi during sunset. Their face, features, and hairstyle must be an exact, photorealistic match and must not be altered. The lighting on the person must perfectly match the soft, pastel hues of the sunset sky, with realistic highlights and their reflection subtly visible in the water. They must be grounded with soft contact shadows consistent with the evening light. Critically, their edges must be flawlessly blended into the background to create a photorealistic composite. Digitally dress them in modern, elegant attire. The composition must capture the temple's reflection in the water. The style should be inspired by National Geographic's photojournalism. The final image must be cinematic, with natural lighting. \nno altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'monuments_template_8',
    name: 'Machu Picchu Sunrise Explorer',
    stackId: 'monuments',
    imageUrl: 'https://images.unsplash.com/photo-1528456024359-86221b229d34?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "A hyper-realistic travel portrait of the person from the provided photo, seamlessly integrated into the Machu Picchu ruins at sunrise. Their face, features, and hairstyle must be an exact match to the user's photo and must not be altered. They must be standing firmly on an ancient stone path or grassy terrace, with the dramatic sunlight streaming through the peaks casting realistic highlights and shadows on them that match the light direction and color. Ensure their integration is seamless, grounding them with accurate contact shadows and perfectly anti-aliased edge blending to create a cohesive, photorealistic image. Digitally dress them in practical trekking gear. The style should be a National Geographic hyper-realistic travel portrait with a grand, cinematic feel. \nNo other tourists, no haze, no over-saturated greens, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
];

const sceneriesTemplates: Template[] = [
  {
    id: 'sceneries_template_1',
    name: 'Himalayan Trek',
    stackId: 'sceneries',
    imageUrl: 'https://images.unsplash.com/photo-1551632811-561732d1e306?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "A hyper-realistic portrait of {input person} trekking through the Himalayas, wearing layered hiking gear. The person's face, features, and hairstyle must be an exact match to the provided photo and must not be altered. Scene details: snow-dusted trail, majestic mountains in the background, sunlight piercing thin clouds, cinematic tone mapping, National Geographic photo realism, crisp focus, earthy textures, adventure mood.\nno unrealistic lighting, no floating person, no cartoon effects, no duplicate faces, no overexposure, no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'sceneries_template_2',
    name: 'Sahara Desert Walk',
    stackId: 'sceneries',
    imageUrl: 'https://images.unsplash.com/photo-1473580044384-7ba9967e16a0?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "A photo of {input person} walking across vast golden dunes in the Sahara Desert, carrying a backpack. The person's face, features, and hairstyle must be an exact match to the provided photo and must not be altered. Scene details: soft sunlight casting long shadows, sand patterns crisp and realistic, warm tones, National Geographic composition, cinematic atmosphere.\nno mirage effects, no sandstorm, no missing limbs, no unnatural shadows, no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'sceneries_template_3',
    name: 'Amazon Rainforest Explorer',
    stackId: 'sceneries',
    imageUrl: 'https://images.unsplash.com/photo-1547036391-4d7a12e8arr0?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "{input person} exploring dense Amazon rainforest. The person's face, features, and hairstyle must be an exact match to the provided photo and must not be altered. Scene details: surrounded by lush green foliage, filtered sunlight through mist, camera capturing droplets and humidity, macro-realistic leaves, cinematic 4K detail, adventure explorer theme.\nno bugs near the face, no blur from rain, no fantasy animals, no over-contrast, no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'sceneries_template_5',
    name: 'Icelandic Waterfall',
    stackId: 'sceneries',
    imageUrl: 'https://images.unsplash.com/photo-1502691879809-5da709295113?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "{input person} standing near a massive Icelandic waterfall. The person's face, features, and hairstyle must be an exact match to the provided photo and must not be altered. Scene details: mist in the air, moss-covered cliffs, dramatic wide-angle composition, hyper-realistic lighting, adventure photography tone, vibrant natural colors.\nno blurry mist blocking face, no surreal rainbow, no multiple waterfalls, no artificial look, no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'sceneries_template_6',
    name: 'Moroccan Market',
    stackId: 'sceneries',
    imageUrl: 'https://images.unsplash.com/photo-1563991300-1123761a2988?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "A candid shot of {input person} walking through a vibrant Moroccan market. The person's face, features, and hairstyle must be an exact match to the provided photo and must not be altered. Scene details: surrounded by colorful fabrics, lanterns, spices, and warm afternoon light. High realism, cinematic depth, travel documentary aesthetic.\nno extra people merging with subject, no duplicate stalls, no distorted architecture, no fake colors, no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'sceneries_template_7',
    name: 'Aurora Borealis Night',
    stackId: 'sceneries',
    imageUrl: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?q=80&w=600&h=800&auto=format&fit=crop',
    prompt: "{input person} standing in front of aurora borealis under a starry night sky, wearing winter clothing. The person's face, features, and hairstyle must be an exact match to the provided photo and must not be altered. Scene details: snow reflecting green and purple light, crisp cinematic clarity, National Geographic hyper-realistic tone, emotional composition.\nno artificial sky patterns, no cartoon aurora, no exposure burn, no fantasy style, no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
];

// Fallback for any other stacks to ensure they have content
const allStackIds = STACKS.map(s => s.id);
const definedStackIds = ['animation', 'aesthetics', 'celebration', 'clothes', 'flex', 'monuments', 'sceneries'];
const remainingStackIds = allStackIds.filter(id => !definedStackIds.includes(id));

const placeholderTemplates = remainingStackIds.flatMap(stackId => {
  const stack = STACKS.find(s => s.id === stackId)!;
  return Array.from({ length: 4 }, (_, i): Template => ({
    id: `${stack.id}_template_${i + 1}`,
    name: `${stack.name} Style ${i + 1}`,
    stackId: stack.id,
    imageUrl: `https://picsum.photos/seed/${stack.id}${i}/600/800`,
    prompt: `Transform the user's image with a professional ${stack.name.toLowerCase()} aesthetic, style ${i+1}. Focus on composition and high-quality details.`,
    aspectRatio: '3:4',
  }));
});


export const TEMPLATES: Template[] = [
  ...animationTemplates,
  ...aestheticsTemplates,
  ...celebrationTemplates,
  ...clothesTemplates,
  ...flexTemplates,
  ...monumentsTemplates,
  ...sceneriesTemplates,
  ...placeholderTemplates,
];